services:
  - type: web
    name: n8n
    env: docker
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile  # adjust if your Dockerfile is in a subfolder
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com/  # Replace with your actual domain if needed
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "yourStrongPassword"
