services:
  - type: web
    name: n8n
    runtime: docker
    branch: main
    repository: https://github.com/Blad-of-despair/n8n
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "your-username"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "your-password"
